language: generic
script:
- bash test.sh
deploy:
  provider: releases
  api_key: D/gedAes3R5F+V/uKHzsp2ak2qzW7EQ4MnD557sTmHJO7uV1h+3V9I79M4f+6aa3rDhHXl8dBlFPVDy6uSewlwM4BsyaEZldh4F7oIoqN/inTlELU4hxGwG5Rw6WWOQEdH6i5Dry++n1L5WjnHb8DknIR29TrqxLJBd1bCV5vjTr1yatOQ616zpASzmV8XY7idkIT6ZGyzsCiF0QAN5BGv+M1aNimZzBoalawbYJF0GJdh6n4sjdSrkGYrFlz2RIPRbsoF5nfVoPU8vwIGVegVk0n823N5NJgdFmP+Ul6WKf2vgH727UAClKJRCnA62yOqOgP6UMvEb9KRLjg3UC5XHtvCNDw6HBxJrZ+3VoubEFNMBuaYo1s69Q2DIQk8wl8uzEusFmRVenPiuEAzqVtq6Oa5+eh91G88K3dmEnRYduOXAOBSBCvM4MsHWV8lHhvW4EAGY97O4YFExhqwWgz9DDveLV8kYxVR4rrMYokOFXEcr7X84aevrbgibJ1Z+5infBBJN40XXTFPMiStrnZsmq+10LhFlXdHmXFHK9uGS/pH3bzy6zTMo52ZHaEyO82DzW/LIFgWteEorMufNfQLQontVU8dzIX3V7ew6B45YZkfg3JlS/HSr7nZE/eo7OGl3JUk+WbWRAQgHRTjZ8CxbYihsMIkImI9rc02iVOcY=
  file: "hello.sh"
  on:
    repo: trainmanrun/scripts-hello-shell
    tags: true